### ISSUE TITLE
Get time to work, using google-maps personal user data

### ISSUE THREAD

**Issue by rutul10** [MZ1387/Smart-Mirror#16]

**Comment by DeftDevDan** [comment]
For time, we can use current location through IP.

http://ipinfo.io/developers

**Comment by rutul10** [comment]
Yea i think we might have to do that. There's way of getting work location through personal scope or Google plus api but people normally don't keep that info updated.

Thank you,
Rutul Patel

On Mar 21, 2017, at 5:02 PM, kptkid <notifications@github.com<mailto:notifications@github.com>> wrote:


For time, we can use current location through IP.

http://ipinfo.io/developers
